name: Update Current Forecast 03

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch data
        run: |
          mkdir -p forecast
          curl "https://my-ocean-api.onrender.com/umishiru_forecast?areaCode=03" \
            -o forecast/03.json

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add forecast/03.json

          git diff --cached --quiet || (
            git commit -m "update forecast 03"
            git push
          )
